# Generated by Django 2.1 on 2020-05-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200413_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='qid',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
